# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Threadbare Haberdashery Handbook
site_url: https://threadbare-docs.readthedocs.io/en/latest/
theme:
  name: material
plugins:
  - search
  - awesome-nav
markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/reference/images/
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
