backend:
  name: github
  repo: endlessm/threadbare-docs
  auth_scope: repo # this is needed to fork the private repo
  branch: main
  base_url: https://a4qdravtfb.execute-api.us-west-1.amazonaws.com
  auth_endpoint: /prod/auth
  squash_merges: true
  open_authoring: true

#media_folder: source/_static/uploads
#public_folder: _static/uploads
publish_mode: editorial_workflow
collections:
  - name: visual_style
    label: Visual Style Guides
    folder: docs/visual_style
    create: true
    fields: &common-fields
      - label: Title
        name: title
        widget: string
      - label: Subtitle
        name: subtitle
        widget: string
        required: false
      - label: Body
        name: body
        widget: markdown

  - name: world
    label: World-building
    folder: source/world
    create: true
    fields: *common-fields

  - name: guides
    label: Guides
    folder: source/world
    create: true
    # TODO: subdirectories
    fields: *common-fields
