backend:
  name: github
  repo: endlessm/threadbare-docs
  auth_scope: repo # this is needed to fork the private repo
  branch: main
  base_url: https://a4qdravtfb.execute-api.us-west-1.amazonaws.com
  auth_endpoint: /prod/auth
  squash_merges: true
  open_authoring: true

media_folder: docs/uploads
public_folder: ../uploads
publish_mode: editorial_workflow
collections:
  - name: pages
    label: Pages
    files:
      - label: Home Page
        name: home
        file: docs/index.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
            required: false
          - label: Body
            name: body
            widget: markdown

  - name: visual_style
    label: Visual Style Guides
    folder: docs/visual_style
    create: true
    media_folder: 'img'
    public_folder: 'img'
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown

  - name: world
    label: World-building
    folder: docs/world
    create: true
    media_folder: 'img'
    public_folder: 'img'
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown

  - name: guides
    label: Guides
    label_singular: Guide
    folder: docs/guides
    create: true
    # TODO: subdirectories
    media_folder: 'img'
    public_folder: 'img'
    path: '{{ subsection }}/{{ slug }}'
    fields:
      - label: Title
        name: title
        widget: string
        required: false
      - label: Subsection
        name: subsection
        widget: select
        options:
          - git_basics
          - godot
      - label: Body
        name: body
        widget: markdown
