backend:
  name: github
  repo: endlessm/threadbare-docs
  auth_scope: repo # this is needed to fork the private repo
  branch: main
  base_url: https://a4qdravtfb.execute-api.us-west-1.amazonaws.com
  auth_endpoint: /prod/auth
  squash_merges: true

media_folder: source/_static/uploads
public_folder: _static/uploads
publish_mode: editorial_workflow
open_authoring: true
collections:
  - name: visual_style
    label: Visual Style
    folder: source/visual_style
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
  - name: world
    label: World-building
    folder: source/world
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
