backend:
  name: github
  repo: endlessm/threadbare-docs
  branch: main
  base_url: https://a4qdravtfb.execute-api.us-west-1.amazonaws.com
  auth_endpoint: /prod/auth

media_folder: source/_static/uploads
public_folder: _static/uploads
collections:
  - name: world
    label: World-building
    folder: source/world
    create: true
    fields:
      - label: Body
        name: body
        widget: markdown
